// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVrIctlchgpKyOdSURCzgbdnTNu9XSNdQ',
    appId: '1:1082347619289:web:120c0ca133879cfa284fc8',
    messagingSenderId: '1082347619289',
    projectId: 'maitexa-15249',
    authDomain: 'maitexa-15249.firebaseapp.com',
    storageBucket: 'maitexa-15249.appspot.com',
    measurementId: 'G-X89PCK3NHV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArRTdpgPhk5xKotevZF16JriRaw5U06Gw',
    appId: '1:1082347619289:android:203e782ae819b685284fc8',
    messagingSenderId: '1082347619289',
    projectId: 'maitexa-15249',
    storageBucket: 'maitexa-15249.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnDT6Kw7VyqlBhfpAcUaxGurLRHPSOgwU',
    appId: '1:1082347619289:ios:90ac36e923d87044284fc8',
    messagingSenderId: '1082347619289',
    projectId: 'maitexa-15249',
    storageBucket: 'maitexa-15249.appspot.com',
    iosBundleId: 'com.example.contactsManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnDT6Kw7VyqlBhfpAcUaxGurLRHPSOgwU',
    appId: '1:1082347619289:ios:90ac36e923d87044284fc8',
    messagingSenderId: '1082347619289',
    projectId: 'maitexa-15249',
    storageBucket: 'maitexa-15249.appspot.com',
    iosBundleId: 'com.example.contactsManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVrIctlchgpKyOdSURCzgbdnTNu9XSNdQ',
    appId: '1:1082347619289:web:a1931d1bd3cc7895284fc8',
    messagingSenderId: '1082347619289',
    projectId: 'maitexa-15249',
    authDomain: 'maitexa-15249.firebaseapp.com',
    storageBucket: 'maitexa-15249.appspot.com',
    measurementId: 'G-RZTCLJQRNR',
  );
}
